

services:

  db:
    container_name: db
    image: postgres:16.2-alpine
    restart: always
    volumes:
      - db_volume_qactf:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    env_file:
      - ./.env

  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - backend_media:/app/media/
      - logs:/app/app/logs

  nginx:
    container_name: proxy
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - backend_media:/media/

volumes:
  db_volume_qactf:
  backend_media:
  logs:
