"""examination model with relationship, scheme, crud, endpoints

Revision ID: 043420d3cabe
Revises: da73f8287221
Create Date: 2023-12-15 11:49:39.453458

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '043420d3cabe'
down_revision = 'da73f8287221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examination',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('examination_user_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examination_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['examination_id'], ['examination.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examination_id', 'user_id', name='constraint_examination_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examination_user_association')
    op.drop_table('examination')
    # ### end Alembic commands ###
