"""solvers for Task

Revision ID: 077e0ee35f8c
Revises: 8bcd3764f5cb
Create Date: 2024-08-23 21:05:09.190036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077e0ee35f8c'
down_revision = '8bcd3764f5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solvers', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('solvers')

    # ### end Alembic commands ###
