"""add second name into profile model

Revision ID: 0c8b90f5b8c4
Revises: b508b9e595d0
Create Date: 2024-07-06 22:43:01.338162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8b90f5b8c4'
down_revision = 'b508b9e595d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('second_name')

    # ### end Alembic commands ###
