"""Added default role

Revision ID: 16786c7048d6
Revises: 41b55aea7689
Create Date: 2023-12-08 21:37:55.669358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16786c7048d6'
down_revision = '41b55aea7689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)

    # ### end Alembic commands ###
