"""fields status for Course

Revision ID: 18cd02859132
Revises: dcdbb676dca5
Create Date: 2024-09-03 16:18:18.194587

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

STATUS = [
    ('available', 'available'),
    ('sealed', 'sealed'),
    ('subscription', 'subscription'),
    ('development', 'development'),
]

# revision identifiers, used by Alembic.
revision = '18cd02859132'
down_revision = 'dcdbb676dca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(choices=STATUS), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
