"""contact_block

Revision ID: 19c8f452647a
Revises: 981474c39706
Create Date: 2024-07-23 23:04:13.553242

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '19c8f452647a'
down_revision = '981474c39706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactinformationblock',
    sa.Column('phones', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contactinformationblock')
    # ### end Alembic commands ###
