"""notification_models

Revision ID: 20d3addee5ba
Revises: 981474c39706
Create Date: 2024-07-30 20:18:41.017469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d3addee5ba'
down_revision = '981474c39706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))
        batch_op.drop_column('description')

    with op.batch_alter_table('notification_user_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_constraint('constraint_notification_user', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_user_association', schema=None) as batch_op:
        batch_op.create_unique_constraint('constraint_notification_user', ['notification_id', 'user_id'])
        batch_op.drop_column('date')
        batch_op.drop_column('viewed')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
