"""fix models relationships

Revision ID: 2348e4831674
Revises: f880265a392e
Create Date: 2023-12-11 13:25:35.014265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2348e4831674'
down_revision = 'f880265a392e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
