"""tariff_cost_model

Revision ID: 3524a52aa5d1
Revises: 5a2d8eed5666
Create Date: 2024-08-24 19:14:38.425032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3524a52aa5d1'
down_revision = '5a2d8eed5666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register', sa.String(), nullable=False))
        batch_op.drop_column('register_')

    with op.batch_alter_table('tariff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariff', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('register')

    op.create_table('question',
    sa.Column('problem', sa.VARCHAR(length=100), nullable=False),
    sa.Column('solution', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem')
    )
    # ### end Alembic commands ###
