"""add model Question

Revision ID: 5a2d8eed5666
Revises: 53fadd799e96
Create Date: 2024-08-13 20:36:59.932459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2d8eed5666'
down_revision = '53fadd799e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('problem', sa.String(length=100), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem')
    )
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_', sa.String(), nullable=False))
        batch_op.drop_column('register')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('register_')

    op.drop_table('question')
    # ### end Alembic commands ###
