"""group user m2m

Revision ID: 5b37c27efb7b
Revises: ce2a08bc6d33
Create Date: 2023-12-11 02:23:26.166882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b37c27efb7b'
down_revision = 'ce2a08bc6d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
