"""new fields in model course

Revision ID: 61d2d0c35e43
Revises: 3772013f6c6a
Create Date: 2024-09-03 21:35:47.881318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d2d0c35e43'
down_revision = '3772013f6c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_', sa.String(), nullable=False))
        batch_op.drop_column('register')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('icon')

    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('register_')

    # ### end Alembic commands ###
