"""user_questions_and_themes

Revision ID: 67b3ce9e2d4f
Revises: 3772013f6c6a
Create Date: 2024-09-03 01:01:14.871118

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '67b3ce9e2d4f'
down_revision = '3772013f6c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'themescategory',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'userquestion',
        sa.Column(
            'from_user_email',
            sqlalchemy_utils.types.email.EmailType(length=255),
            nullable=False,
        ),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'theme',
        sa.Column('themescategory_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ['themescategory_id'],
            ['themescategory.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('register_', sa.String(), nullable=False)
        )
        batch_op.drop_column('register')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('register', sa.VARCHAR(), nullable=False)
        )
        batch_op.drop_column('register_')

    op.drop_table('theme')
    op.drop_table('userquestion')
    op.drop_table('themescategory')
    # ### end Alembic commands ###
