"""add_in_development_field_for_course

Revision ID: 71febb21c593
Revises: 67b3ce9e2d4f
Create Date: 2024-09-09 20:08:50.832502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71febb21c593'
down_revision = '67b3ce9e2d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_development', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('icon')
        batch_op.drop_column('in_development')

    op.create_table('themescategory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('theme',
    sa.Column('themescategory_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['themescategory_id'], ['themescategory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('userquestion',
    sa.Column('from_user_email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
