"""fix image

Revision ID: 77feae2ef366
Revises: 980ad4ecd865
Create Date: 2023-12-21 14:08:38.657377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77feae2ef366'
down_revision = '980ad4ecd865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
