"""fix profile model

Revision ID: 865bf1178361
Revises: 77feae2ef366
Create Date: 2023-12-22 00:53:27.042268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865bf1178361'
down_revision = '77feae2ef366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
