"""time and difficult for Task

Revision ID: 8bcd3764f5cb
Revises: 5a2d8eed5666
Create Date: 2024-08-23 20:47:20.386357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bcd3764f5cb'
down_revision = '5a2d8eed5666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficult', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('time', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('time')
        batch_op.drop_column('difficult')

    # ### end Alembic commands ###
