"""relationship user profile

Revision ID: 9436e9b65a6a
Revises: e21da4ecec18
Create Date: 2023-12-11 22:56:24.072674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9436e9b65a6a'
down_revision = 'e21da4ecec18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('constraint_user', ['user_id'])
        batch_op.create_foreign_key('fk_user_profile', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_profile', type_='foreignkey')
        batch_op.drop_constraint('constraint_user', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
