"""add gender into profile model

Revision ID: 981474c39706
Revises: b1d3664d675b
Create Date: 2024-07-06 23:53:35.733199

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '981474c39706'
down_revision = 'b1d3664d675b'
branch_labels = None
depends_on = None


GENDERS = [
    ('male', 'male'),
    ('female', 'female')
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sqlalchemy_utils.types.choice.ChoiceType(choices=GENDERS), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
