"""updated model fields

Revision ID: 9f0db4b22e80
Revises: 981474c39706
Create Date: 2024-07-24 21:37:14.453381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0db4b22e80'
down_revision = '981474c39706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('my_achievements', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('tests_completed', sa.String(), nullable=False),
    sa.Column('tasks_completed', sa.String(), nullable=False),
    sa.Column('not_passed', sa.String(), nullable=False),
    sa.Column('achievements_week', sa.String(), nullable=False),
    sa.Column('achievements_api', sa.String(), nullable=False),
    sa.Column('achievements_grade', sa.String(), nullable=False),
    sa.Column('achievements_db', sa.String(), nullable=False),
    sa.Column('achievements_month', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('months',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('january', sa.String(), nullable=False),
    sa.Column('february', sa.String(), nullable=False),
    sa.Column('march', sa.String(), nullable=False),
    sa.Column('april', sa.String(), nullable=False),
    sa.Column('may', sa.String(), nullable=False),
    sa.Column('june', sa.String(), nullable=False),
    sa.Column('july', sa.String(), nullable=False),
    sa.Column('august', sa.String(), nullable=False),
    sa.Column('september', sa.String(), nullable=False),
    sa.Column('october', sa.String(), nullable=False),
    sa.Column('november', sa.String(), nullable=False),
    sa.Column('december', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('study', sa.String(), nullable=False),
    sa.Column('secure', sa.String(), nullable=False),
    sa.Column('achievement', sa.String(), nullable=False),
    sa.Column('date_not_found', sa.String(), nullable=False),
    sa.Column('breadcrumb', sa.String(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('secondname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('birthday', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('upload_avatar', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionbanner',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('questions', sa.String(), nullable=False),
    sa.Column('write_us', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secure',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('change_password', sa.String(), nullable=False),
    sa.Column('current_password', sa.String(), nullable=False),
    sa.Column('new_password', sa.String(), nullable=False),
    sa.Column('confirm_password', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register', sa.String(), nullable=False))
        batch_op.drop_column('register_')

    with op.batch_alter_table('common', schema=None) as batch_op:
        batch_op.add_column(sa.Column('save', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('edit', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('upload', sa.String(), nullable=False))

    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required', sa.String(), nullable=False))

    with op.batch_alter_table('help', schema=None) as batch_op:
        batch_op.drop_column('write_us')
        batch_op.drop_column('questions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questions', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('write_us', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.drop_column('required')

    with op.batch_alter_table('common', schema=None) as batch_op:
        batch_op.drop_column('upload')
        batch_op.drop_column('edit')
        batch_op.drop_column('save')

    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('register')

    op.drop_table('secure')
    op.drop_table('questionbanner')
    op.drop_table('profiles')
    op.drop_table('months')
    op.drop_table('achievements')
    # ### end Alembic commands ###
