"""tariff_is_closed_model

Revision ID: 9fe39c8c804e
Revises: 3524a52aa5d1
Create Date: 2024-08-25 02:43:15.638649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe39c8c804e'
down_revision = '3524a52aa5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_closed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariff', schema=None) as batch_op:
        batch_op.drop_column('is_closed')

    # ### end Alembic commands ###
