"""add_new_field_in_course_is_closed

Revision ID: a9fa68c1488d
Revises: 865bf1178361
Create Date: 2024-01-30 20:11:23.112478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fa68c1488d'
down_revision = '865bf1178361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_closed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('is_closed')

    # ### end Alembic commands ###
