"""updated model fields in locale

Revision ID: aa308ff8a214
Revises: 9f0db4b22e80
Create Date: 2024-07-24 22:01:27.418672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa308ff8a214'
down_revision = '9f0db4b22e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profileuser',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('study', sa.String(), nullable=False),
    sa.Column('secure', sa.String(), nullable=False),
    sa.Column('achievement', sa.String(), nullable=False),
    sa.Column('date_not_found', sa.String(), nullable=False),
    sa.Column('breadcrumb', sa.String(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('secondname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('birthday', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('upload_avatar', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('profiles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('locale_id', sa.INTEGER(), nullable=True),
    sa.Column('study', sa.VARCHAR(), nullable=False),
    sa.Column('secure', sa.VARCHAR(), nullable=False),
    sa.Column('achievement', sa.VARCHAR(), nullable=False),
    sa.Column('date_not_found', sa.VARCHAR(), nullable=False),
    sa.Column('breadcrumb', sa.VARCHAR(), nullable=False),
    sa.Column('activity', sa.VARCHAR(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(), nullable=False),
    sa.Column('secondname', sa.VARCHAR(), nullable=False),
    sa.Column('lastname', sa.VARCHAR(), nullable=False),
    sa.Column('birthday', sa.VARCHAR(), nullable=False),
    sa.Column('gender', sa.VARCHAR(), nullable=False),
    sa.Column('upload_avatar', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('profileuser')
    # ### end Alembic commands ###
