"""remove age from profile model

Revision ID: b1d3664d675b
Revises: b3b2fb7b2022
Create Date: 2024-07-06 23:11:54.283835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d3664d675b'
down_revision = 'b3b2fb7b2022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.SMALLINT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
