"""add birthday into profile model

Revision ID: b3b2fb7b2022
Revises: 0c8b90f5b8c4
Create Date: 2024-07-06 23:06:24.952315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b2fb7b2022'
down_revision = '0c8b90f5b8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('birthday')

    # ### end Alembic commands ###
