"""language unique true

Revision ID: b508b9e595d0
Revises: c291b9a2fbe5
Create Date: 2024-06-22 01:32:34.346560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b508b9e595d0'
down_revision = 'c291b9a2fbe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locale', schema=None) as batch_op:
        batch_op.create_unique_constraint('language_unique_constraint', ['language'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locale', schema=None) as batch_op:
        batch_op.drop_constraint('language_unique_constraint', type_='unique')

    # ### end Alembic commands ###
