"""group user m2m fix

Revision ID: bbd832bbe092
Revises: 9436e9b65a6a
Create Date: 2023-12-12 04:32:06.067226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd832bbe092'
down_revision = '9436e9b65a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('association_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('constraint_group_user', ['group_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('association_table', schema=None) as batch_op:
        batch_op.drop_constraint('constraint_group_user', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
