"""locale models

Revision ID: c291b9a2fbe5
Revises: 132f5d88e682
Create Date: 2024-06-19 22:04:55.856481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c291b9a2fbe5'
down_revision = '132f5d88e682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locale',
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('welcome', sa.String(), nullable=False),
    sa.Column('auth_title1', sa.String(), nullable=False),
    sa.Column('auth_title2', sa.String(), nullable=False),
    sa.Column('forgot_password', sa.String(), nullable=False),
    sa.Column('enter', sa.String(), nullable=False),
    sa.Column('register_', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('common',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('all_notification', sa.String(), nullable=False),
    sa.Column('profile', sa.String(), nullable=False),
    sa.Column('ok', sa.String(), nullable=False),
    sa.Column('exit', sa.String(), nullable=False),
    sa.Column('cancel', sa.String(), nullable=False),
    sa.Column('main', sa.String(), nullable=False),
    sa.Column('tasks', sa.String(), nullable=False),
    sa.Column('subscription', sa.String(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('notifications', sa.String(), nullable=False),
    sa.Column('help', sa.String(), nullable=False),
    sa.Column('contacts', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_placeholder', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('login_placeholder', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('password_placeholder', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('message_placeholder', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('support', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('our_contacts', sa.String(), nullable=False),
    sa.Column('phones', sa.String(), nullable=False),
    sa.Column('phone1', sa.String(), nullable=False),
    sa.Column('phone2', sa.String(), nullable=False),
    sa.Column('select_label', sa.String(), nullable=False),
    sa.Column('select_placeholder', sa.String(), nullable=False),
    sa.Column('select_option1', sa.String(), nullable=False),
    sa.Column('select_option2', sa.String(), nullable=False),
    sa.Column('select_option3', sa.String(), nullable=False),
    sa.Column('email_placeholder', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('errors',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('incorect_email', sa.String(), nullable=False),
    sa.Column('required_email', sa.String(), nullable=False),
    sa.Column('required_login', sa.String(), nullable=False),
    sa.Column('required_password', sa.String(), nullable=False),
    sa.Column('requirement_password', sa.String(), nullable=False),
    sa.Column('error400', sa.String(), nullable=False),
    sa.Column('error409', sa.String(), nullable=False),
    sa.Column('error500', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('header',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('modal_title', sa.String(), nullable=False),
    sa.Column('modal_question', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('help',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('questions', sa.String(), nullable=False),
    sa.Column('write_us', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('title1', sa.String(), nullable=False),
    sa.Column('text1', sa.String(), nullable=False),
    sa.Column('text2', sa.String(), nullable=False),
    sa.Column('text3', sa.String(), nullable=False),
    sa.Column('title2', sa.String(), nullable=False),
    sa.Column('text4', sa.String(), nullable=False),
    sa.Column('button_text', sa.String(), nullable=False),
    sa.Column('title3', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restore',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('restore_password', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('button_text', sa.String(), nullable=False),
    sa.Column('modal_title', sa.String(), nullable=False),
    sa.Column('modal_agreements', sa.String(), nullable=False),
    sa.Column('modal_option1', sa.String(), nullable=False),
    sa.Column('modal_option2', sa.String(), nullable=False),
    sa.Column('modal_option3', sa.String(), nullable=False),
    sa.Column('modal_option4', sa.String(), nullable=False),
    sa.Column('modal_check1', sa.String(), nullable=False),
    sa.Column('modal_check2', sa.String(), nullable=False),
    sa.Column('modal_check3', sa.String(), nullable=False),
    sa.Column('modal_check4', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('button_text1', sa.String(), nullable=False),
    sa.Column('button_text2', sa.String(), nullable=False),
    sa.Column('button_text3', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('breadcrumb', sa.String(), nullable=False),
    sa.Column('loading', sa.String(), nullable=False),
    sa.Column('button_text1', sa.String(), nullable=False),
    sa.Column('button_text2', sa.String(), nullable=False),
    sa.Column('button_text3', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('subscription')
    op.drop_table('restore')
    op.drop_table('main')
    op.drop_table('help')
    op.drop_table('header')
    op.drop_table('errors')
    op.drop_table('contacts')
    op.drop_table('common')
    op.drop_table('auth')
    op.drop_table('locale')
    # ### end Alembic commands ###
