"""icon_for_course

Revision ID: dcdbb676dca5
Revises: 3955e7646b3f
Create Date: 2024-09-03 11:01:07.194289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcdbb676dca5'
down_revision = '3955e7646b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_', sa.String(), nullable=False))
        batch_op.drop_column('register')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('icon')

    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('register_')

    # ### end Alembic commands ###
