"""foreingkey user teriff

Revision ID: e21da4ecec18
Revises: 8df1f3e7f3d4
Create Date: 2023-12-11 21:52:01.340149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21da4ecec18'
down_revision = '8df1f3e7f3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tariff_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_tariff', 'tariff', ['tariff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tariff_id')

    # ### end Alembic commands ###
